# Generated by Django 4.1.5 on 2023-02-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('ques', models.CharField(max_length=200)),
                ('opt1', models.CharField(max_length=200)),
                ('opt2', models.CharField(max_length=200)),
                ('opt3', models.CharField(max_length=200)),
                ('opt4', models.CharField(max_length=200)),
                ('correct', models.CharField(max_length=200)),
                ('correct_opt', models.CharField(max_length=10)),
            ],
        ),
    ]
