# Generated by Django 4.1.5 on 2023-02-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_rename_test_lock_task_result_test_unlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('test_status', models.CharField(default='False', max_length=50)),
                ('test_unlock', models.CharField(default='False', max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.task_result')),
            ],
        ),
    ]
