# Generated by Django 4.1.5 on 2023-02-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0006_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
