# Generated by Django 4.1.5 on 2023-02-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_alter_question_correct_opt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_choosen',
            field=models.CharField(default='', max_length=50),
        ),
    ]
